#!/usr/bin/env python
import sys
from optparse import OptionParser
import math
# TODO Use ArgParse once Debian Stabilizes.

def usage():
    print "" 
    sys.exit(0)

def set_parser():
    parser = OptionParser(usage="Usage: joos [OPTION] ... [FILE] ...")
    parser.add_option("-o", "--output",action="store", 
                      type="string", dest="out_file")
    return parser

def safe_open(file,mode):
    try:
        return open(file,mode)
    except IOError as e: 
        print e
        sys.exit(1) 

def file_to_array(file):
    return [x.strip() for x in file] 

def convert_int(i):
    try :
        return int(i)
    except ValueError as e :
        print e
        sys.exit(2)
        
def perc_elem (n, p):
    return int(math.ceil(n*p/100.0)-1)

def calculate_stats(points):
    int_arr = [ convert_int(x) for x in points] 
    stats={}
    if int_arr :
        stats['avg'] = sum(int_arr)/len(int_arr) 
        stats['count'] = len(int_arr)
        int_arr.sort()
        stats[0] = int_arr[0]
        stats[100] = int_arr[-1]
        for i in [50,99,99.9,99.99,95,90]:
            stats[i] = int_arr[perc_elem(len(int_arr),i)] 
        return stats
    else :
        return None

def default_output(result,out):
    '''Takes the result and prints in a default way in output File'''
    out.write("Count = %d\n" % result['count'])
    out.write("Avg = %f\n"%result['avg'])
    for i in [0,50,90,95,99,99.9,99.99,100] :
        out.write("%.2f <= %d\n"%(i,result[i]))

def main():
    parser = set_parser()
    (options, args) = parser.parse_args()
    points = []
    if args:
        for file in args:
            points.extend(file_to_array(safe_open(file,'r'))) 
    else :
        points.extend(file_to_array(sys.stdin))
        
    out = safe_open(options.out_file,'w') if options.out_file else sys.stdout 
    result = calculate_stats(points)
    if result :
        default_output(result,out)        

if __name__ =="__main__":
    main()
